### ISSUE TITLE
cannot crawl youtube mobile

### ISSUE THREAD

**Issue by MohamedFawzy** [s0ph1e/node-website-scraper#161] opened 2016-12-25 23:37 UTC
Cannot crawl any link from youtube mobile site return blank page with html incorrect .

**Comment by s0ph1e** [comment] 2016-12-26 15:16
Hi @MohamedFawzy 

As I can see mobile youtube site [m.youtube.com](https://m.youtube.com/) is using scripts to render. 
`website-scraper` module can correctly handle only static websites, not dynamic. All it does is parsing html and css files. It doesn't execute js files, it only saves them as is.
So all content generated by scripts (like rendering dom elements, loading additional resources) will be not available in result.

**Comment by s0ph1e** [comment] 2016-12-28 21:29
Closing this issue because it is expected behavior for dynamic websites.
If you have more questions feel free to create new issue

**Closed by s0ph1e** 2016-12-28 21:29 UTC
