### ISSUE TITLE
CSS Styles are not applying on Scapped Webpage when User-Agent request header changed

### ISSUE THREAD

**Issue by Jaspreet-Sian** [s0ph1e/node-website-scraper#208] opened 2017-05-21 20:04 UTC
@s0ph1e
  
I tried to scrape webpage with User_Agent request header string

> request: {
>             headers: {
>               'User-Agent': 'Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 4 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/40.0.0 Mobile Safari/535.19'
>             }
>           }

  then scrapped website rendered properly. 
When I change User_Agent request header string to 

> request: {
>             headers: {
>                'User-Agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Mobile Safari/537.36'
>             }
>           }

I am able to scrape css files too with scrapped website but CSS styles are not applied on scrapped website, here is code :  
> var options = {
>           urls: [{
>             url : actualURL
>           }],
>           request: {
>             headers: {
>               'User-Agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Mobile Safari/537.36'
>             }
>           },
>           ignoreErrors : true,
>           directory: DIRECTORY_PATH,
>           subdirectories: [
>             {directory: 'img', extensions: ['.jpg', '.png', '.svg']},
>             {directory: 'js', extensions: ['.js']},
>             {directory: 'css', extensions: ['.css']},
>             {directory: 'fonts', extensions: ['.woff', '.otf', '.ttf', '.eot']}
>           ],
>           httpResponseHandler: (response) => {
>             if (response.statusCode === 404) {
>               return Promise.reject(new Error('status is 404'));
>             }
>             else if (response.statusCode === 444) {
>               console.log("Connection Closed");
>               return Promise.reject(new Error('status is 444'));
>             } else {
>                   return Promise.resolve({
>                       body: response.body,
>                       metadata: {
>                           headers: response.headers,
>                       },
>                   });
>               }
>           },
>           onResourceSaved : (resource) => {
>             console.log(`Resource ${resource} saved to filesystem`);
>           },
>           onResourceError : (resource, err) => {
>             console.log(`Resources ${resource} not saved because of ${err}`);
>           }
>         };

**Comment by s0ph1e** [comment] 2017-05-22 07:58
Hi @Jaspreet-Sian 
Could you please provide url to reproduce issue?

**Comment by s0ph1e** [comment] 2017-05-23 14:04
I found the issue - github uses [Subresource Integrity (SRI)](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) for their pages if user-agent supports it. 

Chrome supports it starting from version 45 - so 
* for `Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 4 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/40.0.0 Mobile Safari/535.19` (chrome 40) page without SRI is returned, 
* but for `Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Mobile Safari/537.36` (chrome 58) page with SRI is returned

When page with SRI is returned - browser checks if hash of resource and hash in `integrity` attribute matches and use resource only if they are equal. Hash are not matching because scraper may update texts of downloaded files and it changes its hash.

I'll thinks about solution and fix it in nearest future.
Thanks for reporting!

**Comment by s0ph1e** [comment] 2017-05-24 07:49
Issue was fixed in version 2.4.1

**Closed by s0ph1e** 2017-05-24 07:49 UTC
